name: CI

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    - name: npm install
      run: npm install
    - name: Build project
      run: npm run-script build
    - name: Check build
      run: ls -l
    - name: dist-to-ft
      uses: isthatcentered/dist-to-ftp@v1
      with:
        user: srv115664
        password: ${{ secrets.PASSWORD }}
        host: ftp-115664.srv.hoster.ru
        # Path to your build folder (usually ./dist or ./public)
        path: ./dist
        # Where to place the files in your ftp
        into: /srv115664.hoster-test.ru
        # Remove existing file inside FTP destination folder
        cleanupExisting: false

