name: CI

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10.16.0
    - name: npm install
      run: npm install
    - name: Build project
      run: npm run-script build
    - name: Check build
      run: |
           cd dist
           ls -l
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
          ftp_server: ftp-115664.srv.hoster.ru
          ftp_username: srv115664
          ftp_password: 4902360q
          remote_dir: srv115664.hoster-test.ru
          


