name: CI

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: npm install
    - name: Build project
      run: ng build --prod
    - name: Check build
      run: ls -l
